Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.become_user = "root"
    # ansible.config_file = "../../../ansible.cfg"
    ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    # ansible.extra_vars = {
    # }
  end
end