
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.become_user = "root"
    ansible.playbook = "playbook.yml"
  end
end
