
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.become_user = "root"
    ansible.playbook = "playbook.yml"
  end
  # It would be nice to get this to work for testing.
  # However, it works in packer and it's time to move on
  # config.vm.provision "shell", inline: "awscli.sh"
end
